# Generated by Django 3.2 on 2023-10-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlesson',
            name='last_viewed_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего просмотра'),
        ),
    ]
